import '../less/logo.less';

import { CustomElement } from '../../../../core/CustomElement.ts';
import { html } from '../../../../helpers/dom.ts';

export class Logo extends CustomElement {
    static element = 'app-logo';

    constructor() {
        super();
        this.updateTheme(); 
        this.observeThemeChanges();
    }

	 template(): string {
        return this.getLightLogo(); 
    }

    /**
     * Returns the ACAT logo SVG content
     * This SVG was generated by the SVG Illustration Generator GPT model (just browse for models and search for it)
     */

	getLightLogo(): string {
		return html`<svg viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">
			<!-- Hood -->
			<path d="M50 80 Q100 10, 150 80 T150 160 Q100 190, 50 160 T50 80" fill="black" stroke="black" stroke-width="4" />
	
			<!-- Cat Face -->
			<circle cx="100" cy="100" r="40" fill="white" stroke="black" stroke-width="4" />
	
			<!-- Cat Ears -->
			<path transform="rotate(-20, 80, 75)" d="M70 75 L80 45 L90 75 Z" fill="black" stroke="black" stroke-width="4" />
			<path transform="rotate(20, 120, 75)" d="M130 75 L120 45 L110 75 Z" fill="black" stroke="black" stroke-width="4" />
	
			<!-- Glasses Frame -->
			<rect x="75" y="90" width="20" height="15" stroke="black" stroke-width="3" fill="none" />
			<rect x="105" y="90" width="20" height="15" stroke="black" stroke-width="3" fill="none" />
			<line x1="95" y1="97" x2="105" y2="97" stroke="black" stroke-width="3" />
	
			<!-- Eyes -->
			<circle cx="85" cy="100" r="5" fill="black" />
			<circle cx="115" cy="100" r="5" fill="black" />
			<circle cx="85" cy="100" r="2" fill="white" />
			<circle cx="115" cy="100" r="2" fill="white" />
	
			<!-- Nose -->
			<path d="M95 110 L100 115 L105 110 Z" fill="black" />
	
			<!-- Mouth -->
			<ellipse cx="100" cy="122" rx="4" ry="5" stroke="black" stroke-width="3" fill="black" />
	
			<!-- Mustățile din stânga  -->
			<line x1="60" y1="110" x2="80" y2="108" stroke="black" stroke-width="2" />
			<line x1="60" y1="115" x2="80" y2="113" stroke="black" stroke-width="2" />
			<line x1="60" y1="120" x2="80" y2="118" stroke="black" stroke-width="2" />
	
			<!-- Mustățile din dreapta  -->
			<line x1="140" y1="110" x2="120" y2="108" stroke="black" stroke-width="2" />
			<line x1="140" y1="115" x2="120" y2="113" stroke="black" stroke-width="2" />
			<line x1="140" y1="120" x2="120" y2="118" stroke="black" stroke-width="2" />
		</svg>`;
	}
	
	getDarkLogo(): string {
		return html`<svg viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">
			<!-- Hood -->
			<path d="M50 80 Q100 10, 150 80 T150 160 Q100 190, 50 160 T50 80" fill="black" stroke="black" stroke-width="4" />
	
			<!-- Cat Face -->
			<circle cx="100" cy="100" r="40" fill="white" stroke="black" stroke-width="4" />
	
			<!-- Cat Ears -->
			<path transform="rotate(-20, 80, 75)" d="M70 75 L80 45 L90 75 Z" fill="black" stroke="black" stroke-width="4" />
			<path transform="rotate(20, 120, 75)" d="M130 75 L120 45 L110 75 Z" fill="black" stroke="black" stroke-width="4" />
	
			<!-- Eyes (closed) -->
			<line x1="77" y1="97" x2="93" y2="97" stroke="black" stroke-width="3" />
			<line x1="107" y1="97" x2="123" y2="97" stroke="black" stroke-width="3" />
	
			<!-- ZZZ for sleeping effect -->
			<text x="160" y="70" font-size="12" font-family="Arial" font-weight="bold" fill="black">Z</text>
			<text x="170" y="60" font-size="14" font-family="Arial" font-weight="bold" fill="black">Z</text>
			<text x="180" y="50" font-size="16" font-family="Arial" font-weight="bold" fill="black">Z</text>
	
			<!-- Nose -->
			<path d="M95 110 L100 115 L105 110 Z" fill="black" />
	
			<!-- Mouth -->
			<ellipse cx="100" cy="122" rx="4" ry="5" stroke="black" stroke-width="3" fill="black" />
	
			<!-- Mustățile din stânga  -->
			<line x1="60" y1="110" x2="80" y2="108" stroke="black" stroke-width="2" />
			<line x1="60" y1="115" x2="80" y2="113" stroke="black" stroke-width="2" />
			<line x1="60" y1="120" x2="80" y2="118" stroke="black" stroke-width="2" />
	
			<!-- Mustățile din dreapta  -->
			<line x1="140" y1="110" x2="120" y2="108" stroke="black" stroke-width="2" />
			<line x1="140" y1="115" x2="120" y2="113" stroke="black" stroke-width="2" />
			<line x1="140" y1="120" x2="120" y2="118" stroke="black" stroke-width="2" />
		</svg>`;
	}
	
    // Detects the theme and updates the logo
    updateTheme = () => {
        const isDark = document.documentElement.classList.contains('dark-theme') || 
                       window.matchMedia('(prefers-color-scheme: dark)').matches;
        this.innerHTML = isDark ? this.getDarkLogo() : this.getLightLogo();
    };

    // Observes theme changes
    observeThemeChanges() {
        const observer = new MutationObserver(() => this.updateTheme());
        observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
        window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', this.updateTheme);
    }
}